name: Build and Deploy Application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/IaC.yml'
      - '.github/workflows/custom-domain.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  ResourceGroup: ent-demo-rg
  SwaName: ent-demo-swa

jobs:
  build-and-test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false

      - name: 'Run Tests'
        run: dotnet test --configuration Release 
          
      - name: Client Build
        run: dotnet publish ./Client/Client.csproj --output ./dist/client

      - name: Api Build
        run: dotnet publish ./Api/Api.csproj --output ./dist/api

      - name: Upload Published Files
        uses: actions/upload-artifact@v4
        with:
          name: Application
          path: dist

      - name: Set the SWA environment
        id: swa-env
        run: |
          if ( "${{ github.event_name }}" == "push" ) {
            echo "ENVIRONMENT=default">> $GITHUB_OUTPUT
          }else{
            echo "ENVIRONMENT=staging${{ github.event.number }}">> $GITHUB_OUTPUT
          }

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # - name: Get SWA deployment token
      #   id: get-secret-from-cli
      #   uses: azure/CLI@v2
      #   with:
      #     azcliversion: 2.42.0
      #     inlineScript: |
      #       SWA_SECRETS=$(az staticwebapp secrets list -n $SwaName -g $ResourceGroup --query 'properties.apiKey' -o tsv )
      #       echo "::add-mask::$SWA_SECRETS"
      #       echo SWA_SECRETS=$SWA_SECRETS >> $GITHUB_OUTPUT

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install SWA CLI
        run:  npm install -g @azure/static-web-apps-cli

      - name: Deploy to SWA
        run:  |
          $Secret = az staticwebapp secrets list -n ${{ env.SwaName }} -g ${{ env.ResourceGroup}} --query 'properties.apiKey' -o tsv
          swa deploy deploy -d $Secret --env ${{ steps.swa-env.outputs.ENVIRONMENT }} -V  silly

      #swa deploy deploy -d ${{ steps.get-secret-from-cli.outputs.SWA_SECRETS }} --env ${{ steps.swa-env.outputs.ENVIRONMENT }} -V  silly

      - name: Get Staging Hostname
        uses: azure/CLI@v2
        if: github.event_name == 'pull_request'
        id: get-hostname
        with:
          inlineScript: |
            SWA_HOSTNAME=$(az staticwebapp environment list -n $SwaName -g $ResourceGroup --query "[?contains(hostname,'${{ steps.swa-env.outputs.ENVIRONMENT }}')].hostname " -o tsv)
            echo $SWA_HOSTNAME
            echo SWA_HOSTNAME=$SWA_HOSTNAME >> $GITHUB_OUTPUT

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Staging Environment Updated

            Test here https://${{ steps.get-hostname.outputs.SWA_HOSTNAME }}

            *Pushed by: @${{ github.actor }}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Remove Staging Environment
        id: get-api-key
        uses: azure/CLI@v2
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az staticwebapp environment delete --name $SwaName --resource-group $ResourceGroup --environment-name staging${{ github.event.number }} --yes
